In [37]:
# Importing necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [38]:
#load the data from dataset
data=pd.read_excel("/content/EmpDetails_1.xlsx")
data

empno     empname  empsal  empdeptno  emppf  emphra  emplta  empexp
0       1       Laxmi   52000         30  0.140   12000   20000       2
1       2        Teja   54000         20  0.120   13000   25000       3
2       3     Hemanth   98665         21  0.150   14000   26000       4
3       4         Sai   59800         30  0.210   12600   30000       1
4       5      Nehath   49000          2  0.150   12559   25000       8
5       6    Praneeth   76665          1  0.140   14000   25000       7
6       7       Divya   51000         15  0.148   15000   27000       5
7       8     Deepthi   53000         17  0.130   19000   27800       4
8       9         Sri   34445         19  0.140   15000   27000       8
9      10     Krishna   48700         16  0.120   18000   20000      10
10     11    Yaswanth   46500         22  0.160   14000   22000       2
11     12    Prasanth   40000         28  0.150   16000   20000      15
12     13    Mahidhar    6666          3  0.160   15400   35000       4
13     14        Banu   55600         12  0.120   18000   25000       5
14     15     Indhira   65000          2  0.130   14600   30000       9
15     16       Priya    9999          7  0.150   18000   20000      10
16     17  Pravallika   69000          8  0.140   17000   35000      11
17     18     Dharani   64500          5  0.150   16800   36000      15
18     19        Rama   70000          4  0.140   17400   38000      13
19     20       Pavan   56000          9  0.140   20000   28000       2
20     21      Pavani    5600          5  0.140   19000   25000       5
21     22      Harika   54000          6  0.120   18000   24000       7
22     23     Harnika   54530          9  0.120   18400   24000       8
23     24      Komali   58200          1  0.130   17000   23000       4
24     25     Sravani   56000         15  0.150   15700   20000       3
25     26      Kriran   49999         15  0.120   15600   21000      15
26     27       Vamsi   48888         12  0.150   15700   21000      11
27     28      Charan   49899         17  0.130   18700   24000      13
28     29      Sruthi   48999         19  0.120   15700   20000       4
29     30     Apoorva   49000         13  0.140   18600   28000       7
30     31      Bhoomi   51111         30  0.150   15370   20000       2
31     32      Renuka   53000         25  0.160   18500   29000       8
32     33     Sriteja   57000         29  0.140   19000   30000       3
33     34  Srikrishna   50000         28  0.130   18900   27000       2
34     35      Kedhar   60000         27  0.140   18750   26000      10
35     36     Kalyani   45000         24  0.150   15000   20000       8
36     37     Bhavana   46500         25  0.180   15470   22000       6
37     39      Taruni   49000         26  0.170   17500   27000       4
38     40       Tarun   60000         12  0.160   20000   32000       7
39     41     Gowtham   65000         16  0.120   20000   31500       1
40     42     Nandhan   65000          1  0.130   20000   32000       8
41     43    Srikanth   63200          7  0.140   19500   29100       2
42     44     Ashwini   65200         18  0.130   19700   29800       4
43     45       Rekha   59200          9  0.140   18000   28100       9
44     46   Manikanta   58700          7  0.150   17990   26500      13
45     47      Sruthi   47888          4  0.140   15000   25000      15
46     48       Gopal   57800          3  0.160   19000   30000       7
47     49     Keerthi   60000         11  0.170   20000   31000       5
48     50      Anusha   58000          1  0.180   19000   30000       6

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   empno      49 non-null     int64  
 1   empname    49 non-null     object 
 2   empsal     49 non-null     int64  
 3   empdeptno  49 non-null     int64  
 4   emppf      49 non-null     float64
 5   emphra     49 non-null     int64  
 6   emplta     49 non-null     int64  
 7   empexp     49 non-null     int64  
dtypes: float64(1), int64(6), object(1)
memory usage: 3.2+ KB


In [40]:
data.head(3)

empno  empname  empsal  empdeptno  emppf  emphra  emplta  empexp
0      1    Laxmi   52000         30   0.14   12000   20000       2
1      2     Teja   54000         20   0.12   13000   25000       3
2      3  Hemanth   98665         21   0.15   14000   26000       4

In [41]:
data.tail(6)

empno    empname  empsal  empdeptno  emppf  emphra  emplta  empexp
43     45      Rekha   59200          9   0.14   18000   28100       9
44     46  Manikanta   58700          7   0.15   17990   26500      13
45     47     Sruthi   47888          4   0.14   15000   25000      15
46     48      Gopal   57800          3   0.16   19000   30000       7
47     49    Keerthi   60000         11   0.17   20000   31000       5
48     50     Anusha   58000          1   0.18   19000   30000       6

In [42]:
# Step 2: Prepare data(catagorical variables)
x = data[['empexp','empdeptno']]  # Independent variable
y = data['empsal']        # Dependent variable

In [43]:
print(type(x))

<class 'pandas.core.frame.DataFrame'>


In [44]:
print(type(y))

<class 'pandas.core.series.Series'>


In [45]:
# Step 3: Split the data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=50)

In [46]:
# Step 4: Train the model
dectree = DecisionTreeClassifier(random_state=42)
dectree.fit(x_train, y_train)

DecisionTreeClassifier(random_state=42)

In [47]:
# Step 5: Make predictions
y_pred = dectree.predict(x_test)

In [48]:
y_pred

array([40000, 48999, 48888, 76665, 48999, 47888, 48888, 63200, 63200,
       58000])

In [49]:
# Step 6: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of the model: {accuracy * 100:.2f}%")

Accuracy of the model: 0.00%


In [50]:
# Step 4: Train the model
randf = RandomForestClassifier()
randf.fit(x_train, y_train)

RandomForestClassifier()

In [51]:
# Step 5: Make predictions
y_pred = randf.predict(x_test)

In [52]:
y_pred

array([48700, 46500,  9999, 76665, 45000, 47888,  9999, 46500, 63200,
       58000])

In [53]:
# Step 6: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of the model: {accuracy * 100:.2f}%")

Accuracy of the model: 0.00%


In [54]:
# Step 4: Train the model
logr = LogisticRegression()
logr.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [55]:
# Step 5: Make predictions
y_pred = logr.predict(x_test)

In [56]:
y_pred

array([40000, 46500, 47888, 76665, 53000, 47888,  9999, 49000, 65000,
       65000])

In [57]:
# Step 6: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of the model: {accuracy * 100:.2f}%")

Accuracy of the model: 0.00%
